/** IPC channel names — single source of truth for main + preload. */
export const IPC = {
  // Push (main → renderer)
  STATS: "stats",
  INVENTORY: "inventory",
  CHESTS: "chests",
  PETS: "pets",
  BOX_TIMERS: "box-timers",
  PRICES_PROGRESS: "prices-progress",
  PRICE_STATUS: "price-status",
  LOOKUP_PRICES: "lookup-prices-snapshot",
  UPDATE_STATUS: "update-status",
  PLAY_NOTIFICATION_SOUND: "play-notification-sound",
  LIVE_MEMORY: "live-memory",
  LIVE_MEMORY_STATUS: "live-memory-status",
  STAGE_RUNS: "stage-runs",
  CATALOG_STATUS: "catalog-status",

  // Invoke (renderer → main)
  GET_STATS: "get-stats",
  GET_INVENTORY: "get-inventory",
  GET_CHESTS: "get-chests",
  GET_PETS: "get-pets",
  GET_BOX_TIMERS: "get-box-timers",
  MARK_BOX_DROPPED: "mark-box-dropped",
  CLEAR_BOX_TIMER: "clear-box-timer",
  SET_BOX_TRACKER_BOXES: "set-box-tracker-boxes",
  SET_BOX_TRACKER_COOLDOWN: "set-box-tracker-cooldown",
  CLEAR_BOX_TRACKER_COOLDOWN: "clear-box-tracker-cooldown",
  SET_BOX_TRACKER_FARM_STAGE: "set-box-tracker-farm-stage",
  CLEAR_BOX_TRACKER_FARM_STAGE: "clear-box-tracker-farm-stage",
  SET_BOX_TRACKER_NOTIFY: "set-box-tracker-notify",
  SET_BOX_TRACKER_SORT_ORDER: "set-box-tracker-sort-order",
  PREVIEW_NOTIFICATION_SOUND: "preview-notification-sound",
  GET_CONFIG: "get-config",
  SAVE_CONFIG: "save-config",
  PICK_SAVE_FILE: "pick-save-file",
  PRICES_STATUS: "prices-status",
  PRICES_REFRESH: "prices-refresh",
  PRICES_REFRESH_ITEM: "prices-refresh-item",
  SET_CURRENCY: "set-currency",
  MARKET_AUTO_SCAN_TOGGLE: "market:auto-scan:toggle",
  GET_DATA_PATHS: "get-data-paths",
  CLEAR_APP_DATA: "clear-app-data",
  CLEAR_DIAGNOSTIC_LOGS: "clear-diagnostic-logs",
  LOG_RENDERER_ERROR: "log-renderer-error",
  GET_UPDATE_STATUS: "get-update-status",
  UPDATE_CHECK: "update-check",
  UPDATE_DOWNLOAD: "update-download",
  UPDATE_QUIT_AND_INSTALL: "update-quit-and-install",
  GET_LOOKUP_CATALOG: "get-lookup-catalog",
  GET_LOOKUP_SOURCES: "get-lookup-sources",
  GET_LOOKUP_SYNTHESIS_MODEL: "get-lookup-synthesis-model",
  GET_OFFERINGS: "get-offerings",
  GET_LOOKUP_PRICES: "get-lookup-prices",
  GET_LIVE_MEMORY: "get-live-memory",
  GET_LIVE_MEMORY_STATUS: "get-live-memory-status",
  GET_STAGE_RUNS: "get-stage-runs",
  LOOT_RESET_BOX: "loot-reset-box",
  LOOT_RESET_ALL: "loot-reset-all",
  LOOT_RECLASSIFY_ITEM: "loot-reclassify-item",
  LOOT_AUTO_CLASSIFY_TOGGLE: "loot:auto-classify:toggle",
  LOOT_AUTO_CLASSIFY_STATE: "loot:auto-classify:state",
  LOOT_PROMPT_CLASSIFY: "loot:prompt:classify",
  LOOT_PROMPT_RESOLVE: "loot:prompt:resolve",
  GET_CATALOG_STATUS: "get-catalog-status",
  CATALOG_REFRESH: "catalog-refresh",
  GET_LOCALE_DATA: "get-locale-data",

  // Send (renderer → main, no response)
  RESET: "reset",
  OPEN_OVERLAY: "open-overlay",
  OPEN_BOX_TRACKER: "open-box-tracker",
  CLOSE_BOX_TRACKER: "close-box-tracker",
  MINIMIZE_BOX_TRACKER: "minimize-box-tracker",
  SHOW_MAIN: "show-main",
  CLOSE_OVERLAY: "close-overlay",
  PRICES_CANCEL: "prices-cancel",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];

/** All channels that must have preload wiring (for contract tests). */
export const IPC_INVOKE_CHANNELS = [
  IPC.GET_STATS,
  IPC.GET_INVENTORY,
  IPC.GET_CHESTS,
  IPC.GET_PETS,
  IPC.GET_BOX_TIMERS,
  IPC.MARK_BOX_DROPPED,
  IPC.CLEAR_BOX_TIMER,
  IPC.SET_BOX_TRACKER_BOXES,
  IPC.SET_BOX_TRACKER_COOLDOWN,
  IPC.CLEAR_BOX_TRACKER_COOLDOWN,
  IPC.SET_BOX_TRACKER_FARM_STAGE,
  IPC.CLEAR_BOX_TRACKER_FARM_STAGE,
  IPC.SET_BOX_TRACKER_NOTIFY,
  IPC.SET_BOX_TRACKER_SORT_ORDER,
  IPC.GET_CONFIG,
  IPC.SAVE_CONFIG,
  IPC.PICK_SAVE_FILE,
  IPC.PRICES_STATUS,
  IPC.PRICES_REFRESH,
  IPC.PRICES_REFRESH_ITEM,
  IPC.SET_CURRENCY,
  IPC.MARKET_AUTO_SCAN_TOGGLE,
  IPC.GET_DATA_PATHS,
  IPC.CLEAR_APP_DATA,
  IPC.CLEAR_DIAGNOSTIC_LOGS,
  IPC.LOG_RENDERER_ERROR,
  IPC.GET_UPDATE_STATUS,
  IPC.UPDATE_CHECK,
  IPC.UPDATE_DOWNLOAD,
  IPC.UPDATE_QUIT_AND_INSTALL,
  IPC.GET_LOOKUP_CATALOG,
  IPC.GET_LOOKUP_SOURCES,
  IPC.GET_LOOKUP_SYNTHESIS_MODEL,
  IPC.GET_OFFERINGS,
  IPC.GET_LOOKUP_PRICES,
  IPC.GET_LIVE_MEMORY,
  IPC.GET_LIVE_MEMORY_STATUS,
  IPC.GET_STAGE_RUNS,
  IPC.LOOT_RESET_BOX,
  IPC.LOOT_RESET_ALL,
  IPC.LOOT_RECLASSIFY_ITEM,
  IPC.LOOT_AUTO_CLASSIFY_TOGGLE,
  IPC.LOOT_AUTO_CLASSIFY_STATE,
  IPC.GET_CATALOG_STATUS,
  IPC.CATALOG_REFRESH,
  IPC.GET_LOCALE_DATA,
] as const;

export const IPC_SEND_CHANNELS = [
  IPC.RESET,
  IPC.OPEN_OVERLAY,
  IPC.OPEN_BOX_TRACKER,
  IPC.CLOSE_BOX_TRACKER,
  IPC.MINIMIZE_BOX_TRACKER,
  IPC.SHOW_MAIN,
  IPC.CLOSE_OVERLAY,
  IPC.PRICES_CANCEL,
  IPC.LOOT_PROMPT_RESOLVE,
] as const;

export const IPC_PUSH_CHANNELS = [
  IPC.STATS,
  IPC.INVENTORY,
  IPC.CHESTS,
  IPC.PETS,
  IPC.BOX_TIMERS,
  IPC.PRICES_PROGRESS,
  IPC.PRICE_STATUS,
  IPC.LOOKUP_PRICES,
  IPC.UPDATE_STATUS,
  IPC.PLAY_NOTIFICATION_SOUND,
  IPC.LIVE_MEMORY,
  IPC.LIVE_MEMORY_STATUS,
  IPC.STAGE_RUNS,
  IPC.LOOT_PROMPT_CLASSIFY,
  IPC.CATALOG_STATUS,
] as const;
